apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: worker-service
  template:
    metadata:
      labels:
        component: worker-service
    spec:
      containers:
        - name: worker-service
          image: yogitubadzin/multi-worker-service
          env:
            - name: REDIS_HOST
              value: redis-cluster-ip-service
            - name: REDIS_PORT
              value: '6379'
